### ISSUE TITLE
How I can use this module with gulp-browserify?

### ISSUE THREAD

**Issue by unclechu** [quarterto/Anyify#5]
How I can define transformer for `gulp-browserify`? For example for `livescript`?

**Comment by quarterto** [comment]
Note that gulp-browserify is deprecated, you should be using plain browserify with vinyl-source-stream as detail in the [Gulp docs](https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-transforms.md).

You can configure Anyify programatically by passing options to `.transform`:

```js
var b = browserify(...);
b.transform('anyify', {
  'ls': 'livescript?compile'
});
```

Hope this helps!
